---
sudo: false
dist: trusty
language: ruby
cache: bundler
bundler_args: --without system_tests development
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_VERSION="~> 3.0" CHECK=validate
  - rvm: 1.8.7
    env: PUPPET_VERSION="~> 4.0" CHECK=validate
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0" CHECK=validate
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.0" CHECK=validate
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 3.0" CHECK=validate
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.0" CHECK=validate
  - rvm: 2.2.6
    env: PUPPET_VERSION="~> 3.0" CHECK=validate
  - rvm: 2.2.6
    env: PUPPET_VERSION="~> 4.0" CHECK=validate
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
